%% SEARCH CONTOUR STRUCTURE
%
% Search the rt structure for SOPClassID and SOPInstanceID in order to
% replace the old id's with the ones generated by the Matlab anonymizer.
%
% Developed by: Ulrik L. Stephansen & Jens T. Olesen
%
%%

function out = searchstruct(structname, searchstr, replacestr)

% Search the structure recursively by calling the same function

out = structfun(@(x) replaceUID(x, searchstr, replacestr), structname, 'UniformOutput',false);

end

function out = replaceUID(in, searchstr, replacestr)
 
% The rt structure tree is searched until a text field is found.

    if ischar(in)
        
        % If the text field and its contents matches the old SOP id, the 
        % new SOP id is written 
        
        out = strrep(in, searchstr, replacestr);
        
    elseif isstruct(in)
        
        % If only another structure was found, the function continues in
        % the new tree
        
        out = structfun(@(x) replaceUID(x, searchstr, replacestr), in, 'UniformOutput',false);
    
    else
        
        out = in;
    
    end
end
